title: Juan's Website
#iconURL: assets/image.png
gifURL: assets/icons.gif
#theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  linkedin: juan-camilo-jojoa-sanchez-956212116/
  github: juanjjs

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 12078
google_analytics: UA-NNNNNNNN-N